services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: mnist-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: mnist-streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/api/v1/predict
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: mnist-network 