version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-nicoooo972/mnist}/mnist-backend:develop
    container_name: mnist-backend-staging
    ports:
      - "8010:8000"  # Port différent pour staging
    volumes:
      - ./models:/app/models:ro
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - ENV=staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-nicoooo972/mnist}/mnist-frontend:develop
    container_name: mnist-frontend-staging
    ports:
      - "8511:8501"  # Port différent pour staging
    environment:
      - API_URL=http://backend:8000/api/v1/predict
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - ENV=staging
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: mnist-staging-network 